create table tbl1 (
  id   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,    -- fails
  --id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- works
  name text   NOT NULL               
);
insert into tbl1 (name) values ('Tommy');
select * from tbl1; -- 1;"Tommy"
update tbl1 set name = 'Bobby' where id = 1;
